set(SRC_FILES
    core/App.cpp
    cards/Card.cpp
    combat/CombatArena.cpp
    cards/CombatCard.cpp
    cards/WanderingCard.cpp
    cards/AnimalCard.cpp
    cards/MonsterCard.cpp
    core/CardFactory.cpp
    core/CardManager.cpp
    cards/CardPack.cpp
    ui/CheatMenu.cpp
    combat/FloatingTextManager.cpp
    core/TaskScheduler.cpp
    ui/UIManager.cpp
    core/EventManager.cpp
    core/RecipeManager.cpp
    core/main.cpp
)

set(INCLUDE_FILES
    core/App.hpp
    data/GameConstants.hpp
    data/ISpawnListener.hpp
    cards/Card.hpp
    data/CardData.hpp
    cards/CardPack.hpp
    core/CardFactory.hpp
    cards/CombatCard.hpp
    cards/WanderingCard.hpp
    cards/AnimalCard.hpp
    cards/MonsterCard.hpp
    cards/CharacterCard.hpp
    cards/BuildingCard.hpp
    cards/StructureCard.hpp
    cards/WarehouseCard.hpp
    cards/ResourceCard.hpp
    cards/FoodCard.hpp
    cards/CoinCard.hpp
    cards/IdeaCard.hpp
    cards/LocationCard.hpp
    cards/EquipmentCard.hpp
    cards/Sellslot.hpp
    combat/CombatArena.hpp
    combat/AttackResolver.hpp
    data/EffectData.hpp
    core/CardManager.hpp
    core/EventManager.hpp
    core/RecipeManager.hpp
    core/TaskScheduler.hpp
    ui/UIManager.hpp
    ui/CheatMenu.hpp
    combat/FloatingTextManager.hpp
    ui/BackgroundImage.hpp
    ui/Button.hpp
    ui/TimeBar.hpp
    cards/BlankSlot.hpp
    cards/MagicGlue.hpp
    cards/CoinChest.hpp
    cards/Hotpot.hpp
    cards/ResourceChest.hpp
    nlohmann/json.hpp
)

set(TEST_FILES
    CombatTests.cpp
)
