set(SRC_FILES
    App.cpp
    Card.cpp
    CardManager.cpp
    CardPack.cpp
    UIManager.cpp
    EventManager.cpp
    RecipeManager.cpp
    main.cpp
)

set(INCLUDE_FILES
    App.hpp
    BackgroundImage.hpp
    Button.hpp
    Card.hpp
    CharacterCard.hpp
    CardData.hpp
    CardManager.hpp
    CardPack.hpp
    CoinCard.hpp
    ResourceCard.hpp
    UIManager.hpp
    EventManager.hpp
    RecipeManager.hpp
)

set(TEST_FILES
)
